version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: token-bucket-app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    # Uncomment the next line if you want to see the logs interactively
    # tty: true
